services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ticket
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: ticket
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
